export default {
    SET_ALERT: 'SET_ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT',
    

    SET_LOGGED_USER: 'SET_LOGGED_USER',
    DELETE_LOGGED_USER: 'DELETE_LOGGED_USER',

    
    SET_REGIONS: 'SET_REGIONS',
    SET_SUB_REGIONS: 'SET_SUB_REGIONS',
    SET_CITIES: 'SET_CITIES',
    

    SET_EMPLOYEES_OEPG: 'SET_EMPLOYEES_OEPG',
    ADD_EMPLOYEE_OEPG: 'ADD_EMPLOYEE_OEPG',
    UPDATE_EMPLOYEE_OEPG: 'UPDATE_EMPLOYEE_OEPG',
    DELETE_EMPLOYEE_OEPG: 'DELETE_EMPLOYEE_OEPG',
    SET_EMPLOYEES_OEPG_LOADING: 'SET_EMPLOYEES_OEPG_LOADING',
    REMOVE_EMPLOYEES_OEPG_LOADING: 'REMOVE_EMPLOYEES_OEPG_LOADING',

    SET_CURRENT_EMPLOYEE_OEPG: 'SET_CURRENT_EMPLOEE_OEPG',
    SET_CURRENT_EMPLOYEE_OEPG_LOADING: 'SET_CURRENT_EMPLOYEE_OEPG_LOADING',
    REMOVE_CURRENT_EMPLOYEE_OEPG_LOADING: 'REMOVE_CURRENT_EMPLOYEE_OEPG_LOADING',


    SET_FAMILIES: 'SET_FAMILIES',
    ADD_FAMILY: 'ADD_FAMILY',
    UPDATE_FAMILY: 'UPDATE_FAMILY',
    DELETE_FAMILY: 'DELETE_FAMILY',
    SET_FAMILIES_LOADING: 'SET_FAMILIES_LOADING',
    REMOVE_FAMILIES_LOADING: 'REMOVE_FAMILIES_LOADING',

    SET_CURRENT_FAMILY: 'SET_CURRENT_FAMILY',
    ADD_CHILD_TO_CURRENT_FAMILY: 'ADD_CHILD_TO_CURRENT_FAMILY',
    REMOVE_CHILD_FROM_CURRENT_FAMILY: 'REMOVE_CHILD_FROM_CURRENT_FAMILY',


    SET_CHILDREN: 'SET_CHILDREN',
    ADD_CHILD: 'ADD_CHILD',
    UPDATE_CHILD: 'UPDATE_CHILD',
    DELETE_CHILD: 'DELETE_CHILD',
    SET_CHILDREN_LOADING: 'SET_CHILDREN_LOADING',
    REMOVE_CHILDREN_LOADING: 'REMOVE_CHILDREN_LOADING',

    SET_CURRENT_CHILD: 'SET_CURRENT_CHILD',
    SET_CURRENT_CHILD_LOADING: 'SET_CURRENT_CHILD_LOADING',
    REMOVE_CURRENT_CHILD_LOADING: 'REMOVE_CURRENT_CHILD_LOADING',
};