export default {
    SET_ERROR: 'SET_ERROR',
    SET_LOGGED_USER: 'SET_LOGGED_USER',
    SET_CHILDREN: 'SET_CHILDREN',
    
    SET_EMPLOYEES_OEPG: 'SET_EMPLOYEES_OEPG',
    DELETE_EMPLOYEE_OEPG: 'DELETE_EMPLOYEE_OEPG',

    SET_FAMILIES: 'SET_FAMILIES',
    DELETE_FAMILY: 'DELETE_FAMILY',
};