export default {
    SET_ERROR: 'SET_ERROR',


    SET_ALERT: 'SET_ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT',
    

    SET_LOGGED_USER: 'SET_LOGGED_USER',
    DELETE_LOGGED_USER: 'DELETE_LOGGED_USER',

    
    SET_REGIONS: 'SET_REGIONS',
    SET_SUB_REGIONS: 'SET_SUB_REGIONS',
    SET_CITIES: 'SET_CITIES',
    

    SET_EMPLOYEES_OEPG: 'SET_EMPLOYEES_OEPG',
    ADD_EMPLOYEE_OEPG: 'ADD_EMPLOYEE_OEPG',
    UPDATE_EMPLOYEE_OEPG: 'UPDATE_EMPLOYEE_OEPG',
    DELETE_EMPLOYEE_OEPG: 'DELETE_EMPLOYEE_OEPG',

    SET_CURRENT_EMPLOYEE_OEPG: 'SET_CURRENT_EMPLOEE_OEPG',


    SET_FAMILIES: 'SET_FAMILIES',
    DELETE_FAMILY: 'DELETE_FAMILY',

    SET_CURRENT_FAMILY: 'SET_CURRENT_FAMILY',
    ADD_CHILD_TO_CURRENT_FAMILY: 'ADD_CHILD_TO_CURRENT_FAMILY',
    REMOVE_CHILD_FROM_CURRENT_FAMILY: 'REMOVE_CHILD_FROM_CURRENT_FAMILY',


    SET_CHILDREN: 'SET_CHILDREN',
    DELETE_CHILD: 'DELETE_CHILD',
};